// src/components/ColorControl.tsx
import { useEffect, useRef } from 'react';
import { mountColorControl, type ColorControlProps } from '../color-control';

export function ColorControl(props: ColorControlProps) {
  const host = useRef<HTMLDivElement>(null);
  const control = useRef<ReturnType<typeof mountColorControl>>();
  const latest = useRef(props);
  latest.current = props;
  useEffect(() => {
    control.current = mountColorControl(host.current!, latest.current);
    return () => control.current?.destroy();
  }, []);
  useEffect(() => { control.current?.update(props); });
  return <div ref={host} className="dialkit-color-host" />;
}

// src/solid/components/ColorControl.tsx
import { createEffect, onCleanup, onMount } from 'solid-js';
import { mountColorControl, type ColorControlProps } from '../../color-control';

export function ColorControl(props: ColorControlProps) {
  let host!: HTMLDivElement;
  let control: ReturnType<typeof mountColorControl> | undefined;
  onMount(() => {
    control = mountColorControl(host, { ...props });
    createEffect(() => control?.update({ label: props.label, value: props.value, onChange: props.onChange }));
  });
  onCleanup(() => control?.destroy());
  return <div ref={host} class="dialkit-color-host" />;
}
