// src/components/EasingVisualization.tsx
import { useEffect, useRef } from 'react';
import { mountEasingVisualization, type EasingVisualizationProps } from '../easing-control';

export { easingPresets } from '../easing-geometry';

export function EasingVisualization(props: EasingVisualizationProps) {
  const host = useRef<HTMLDivElement>(null);
  const control = useRef<ReturnType<typeof mountEasingVisualization>>();
  const latest = useRef(props);
  latest.current = props;
  useEffect(() => {
    control.current = mountEasingVisualization(host.current!, latest.current);
    return () => control.current?.destroy();
  }, []);
  useEffect(() => { control.current?.update(props); });
  return <div ref={host} className="dialkit-easing-host" />;
}

// src/solid/components/EasingVisualization.tsx
import { createEffect, onCleanup, onMount } from 'solid-js';
import { mountEasingVisualization, type EasingVisualizationProps } from '../../easing-control';

export { easingPresets } from '../../easing-geometry';

export function EasingVisualization(props: EasingVisualizationProps) {
  let host!: HTMLDivElement;
  let control: ReturnType<typeof mountEasingVisualization> | undefined;
  onMount(() => {
    control = mountEasingVisualization(host, { ...props });
    createEffect(() => control?.update({ easing: props.easing, onChange: props.onChange }));
  });
  onCleanup(() => control?.destroy());
  return <div ref={host} class="dialkit-easing-host" />;
}
