// src/components/Folder.tsx
import { activateOnKey } from '../control-keyboard';
import { useState, ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ICON_PANEL, ICON_CHEVRON } from '../icons';

interface FolderProps {
  title: string;
  children: ReactNode;
  defaultOpen?: boolean;
  open?: boolean;
  isRoot?: boolean;
  inline?: boolean;
  onOpenChange?: (isOpen: boolean) => void;
  toolbar?: ReactNode;
}

export function Folder({ title, children, open, defaultOpen = true, isRoot = false, inline = false, onOpenChange, toolbar }: FolderProps) {
  const [localOpen, setIsOpen] = useState(defaultOpen);
  const isOpen = open ?? localOpen;
  const isCollapsed = !isOpen;

  const handleToggle = () => {
    if (inline && isRoot) return;
    const next = !isOpen;
    setIsOpen(next);
    onOpenChange?.(next);
  };

  const folderContent = (
    <div
      className={`dialkit-folder ${isRoot ? 'dialkit-folder-root' : ''}`}
      data-open={String(isOpen)}
    >
      <div className={`dialkit-folder-header ${isRoot ? 'dialkit-panel-header' : ''}`} onClick={handleToggle}>
        <div className="dialkit-folder-header-top" role={inline && isRoot ? undefined : "button"} tabIndex={inline && isRoot ? undefined : 0} aria-label={title} aria-expanded={isOpen} onKeyDown={(e) => activateOnKey(e, handleToggle)}>
          {isRoot ? (
            isOpen && (
              <div className="dialkit-folder-title-row">
                <span className="dialkit-folder-title dialkit-folder-title-root">
                  {title}
                </span>
              </div>
            )
          ) : (
            <div className="dialkit-folder-title-row">
              <span className="dialkit-folder-title">
                {title}
              </span>
            </div>
          )}
          {isRoot && !inline && (
            <svg
              className="dialkit-panel-icon"
              viewBox="0 0 16 16"
              fill="none"
            >
              <path opacity="0.5" d={ICON_PANEL.path} fill="currentColor"/>
              {ICON_PANEL.circles.map((c, i) => (
                <circle key={i} cx={c.cx} cy={c.cy} r={c.r} fill="currentColor" stroke="currentColor" strokeWidth="1.25"/>
              ))}
            </svg>
          )}
          {!isRoot && (
            <motion.svg
              className="dialkit-folder-icon"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              initial={false}
              animate={{ rotate: isOpen ? 0 : 180 }}
              transition={{ type: 'spring', visualDuration: 0.35, bounce: 0.15 }}
            >
              <path d={ICON_CHEVRON} />
            </motion.svg>
          )}
        </div>

        {isRoot && toolbar && isOpen && (
          <div className="dialkit-panel-toolbar" onClick={(e) => e.stopPropagation()}>
            {toolbar}
          </div>
        )}
      </div>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            className="dialkit-folder-content"
            initial={isRoot ? undefined : { height: 0, opacity: 0 }}
            animate={isRoot ? undefined : { height: 'auto', opacity: 1 }}
            exit={isRoot ? undefined : { height: 0, opacity: 0 }}
            transition={isRoot ? undefined : { type: 'spring', visualDuration: 0.35, bounce: 0.1 }}
            style={isRoot ? undefined : { clipPath: 'inset(0 -20px)' }}
          >
            <div className="dialkit-folder-inner">{children}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );

  if (isRoot) {
    if (inline) {
      return (
        <div className="dialkit-panel-inner dialkit-panel-inline">
          {folderContent}
        </div>
      );
    }

    const panelStyle = isOpen
      ? { width: 280, height: 'auto' as const, maxHeight: 'calc(100dvh - 32px)', overflowY: 'auto' as const, borderRadius: 14, boxShadow: 'var(--dial-shadow)', cursor: undefined as string | undefined }
      : { width: 42, height: 42, borderRadius: '50%', boxSizing: 'border-box' as const, boxShadow: 'var(--dial-shadow-collapsed)', overflow: 'hidden' as const, cursor: 'pointer' as const };

    return (
      <motion.div
        className="dialkit-panel-inner"
        tabIndex={-1}
        style={panelStyle}
        onClick={!isOpen ? handleToggle : undefined}
        data-collapsed={isCollapsed}
        whileTap={!isOpen ? { scale: 0.9 } : undefined}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        {folderContent}
      </motion.div>
    );
  }

  return folderContent;
}

// src/solid/components/Folder.tsx
import { activateOnKey } from '../../control-keyboard';
import { createSignal, createEffect, on, onCleanup, Show, JSX } from 'solid-js';
import { animate } from 'motion';
import { ICON_CHEVRON } from '../../icons';
import type { AnimationHandle } from '../primitives';
import { RootPanel } from './RootPanel';

interface FolderProps {
  title: string;
  children: JSX.Element;
  defaultOpen?: boolean;
  open?: boolean;
  onOpenChange?: (isOpen: boolean) => void;
  /** @deprecated Use RootPanel instead; kept for backwards compatibility. */
  isRoot?: boolean;
  /** @deprecated Only meaningful with isRoot. */
  inline?: boolean;
  /** @deprecated Only meaningful with isRoot. */
  toolbar?: JSX.Element;
  /** @deprecated Only meaningful with isRoot. */
  panelHeightOffset?: number;
}

const sectionTransition = { type: 'spring' as const, visualDuration: 0.35, bounce: 0.1 };

/** Collapsible section with animated height/opacity and rotating chevron. */
export function Folder(props: FolderProps) {
  // Root panels are a different component; delegate for old call sites.
  if (props.isRoot) {
    return <RootPanel {...props} />;
  }

  const [localOpen, setIsOpen] = createSignal(props.defaultOpen ?? true);
  const isOpen = () => props.open ?? localOpen();
  const [contentMounted, setContentMounted] = createSignal(props.open ?? props.defaultOpen ?? true);
  let skipFirstAnim = props.open ?? props.defaultOpen ?? true;
  let sectionContentRef: HTMLDivElement | undefined;
  let sectionAnim: AnimationHandle | null = null;
  let chevronRef: SVGSVGElement | undefined;
  let chevronAnim: AnimationHandle | null = null;

  onCleanup(() => {
    sectionAnim?.stop();
    chevronAnim?.stop();
  });

  // Chevron renders at its resting angle; only animate on changes.
  createEffect(on(isOpen, (open) => {
    if (!chevronRef) return;
    chevronAnim?.stop();
    chevronAnim = animate(
      chevronRef,
      { rotate: open ? 0 : 180 },
      { type: 'spring', visualDuration: 0.35, bounce: 0.15 }
    );
  }, { defer: true }));

  createEffect(on(isOpen, (next) => {
    if (next) {
      sectionAnim?.stop();
      sectionAnim = null;
      if (sectionContentRef) {
        // If close was interrupted, animate the section back open.
        sectionAnim = animate(
          sectionContentRef,
          { height: 'auto', opacity: 1 },
          {
            ...sectionTransition,
            onComplete: () => {
              sectionAnim = null;
            },
          }
        );
      } else {
        // If fully unmounted, mount and let the ref callback run the enter animation.
        setContentMounted(true);
      }
    } else if (sectionContentRef) {
      const currentHeight = sectionContentRef.getBoundingClientRect().height;
      sectionContentRef.style.height = `${currentHeight}px`;
      sectionAnim?.stop();
      sectionAnim = animate(
        sectionContentRef,
        { height: 0, opacity: 0 },
        {
          ...sectionTransition,
          onComplete: () => {
            setContentMounted(false);
            sectionAnim = null;
            sectionContentRef = undefined;
          },
        }
      );
    } else {
      setContentMounted(false);
    }
  }, { defer: true }));

  const handleToggle = () => {
    const next = !isOpen();
    setIsOpen(next);
    props.onOpenChange?.(next);
  };

  return (
    <div class="dialkit-folder" data-open={String(isOpen())}>
      <div class="dialkit-folder-header" onClick={handleToggle}>
        <div class="dialkit-folder-header-top" role={false ? undefined : "button"} tabIndex={false ? undefined : 0} aria-label={props.title} aria-expanded={isOpen()} onKeyDown={(e) => activateOnKey(e, handleToggle)}>
          <div class="dialkit-folder-title-row">
            <span class="dialkit-folder-title">{props.title}</span>
          </div>

          <svg
            ref={chevronRef}
            class="dialkit-folder-icon"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            style={{ transform: `rotate(${(props.open ?? props.defaultOpen ?? true) ? 0 : 180}deg)` }}
          >
            <path d={ICON_CHEVRON} />
          </svg>
        </div>
      </div>

      <Show when={contentMounted()}>
        <div
          ref={(el) => {
            sectionContentRef = el;
            if (skipFirstAnim) {
              skipFirstAnim = false;
              return;
            }

            sectionAnim?.stop();
            el.style.height = '0px';
            el.style.opacity = '0';
            sectionAnim = animate(
              el,
              { height: 'auto', opacity: 1 },
              {
                ...sectionTransition,
                onComplete: () => {
                  sectionAnim = null;
                },
              }
            );
          }}
          class="dialkit-folder-content"
          style={{ 'clip-path': 'inset(0 -20px)' }}
        >
          <div class="dialkit-folder-inner">{props.children}</div>
        </div>
      </Show>
    </div>
  );
}
