// src/components/ImageControl.tsx
import { useEffect, useRef } from 'react';
import { mountImageControl, type ImageControlProps } from '../image-control';

export function ImageControl(props: ImageControlProps) {
  const host = useRef<HTMLDivElement>(null);
  const control = useRef<ReturnType<typeof mountImageControl>>();
  const latest = useRef(props);
  latest.current = props;
  useEffect(() => {
    control.current = mountImageControl(host.current!, latest.current);
    return () => control.current?.destroy();
  }, []);
  useEffect(() => { control.current?.update(props); });
  return <div ref={host} className="dialkit-image-host" />;
}

// src/solid/components/ImageControl.tsx
import { createEffect, onCleanup, onMount } from 'solid-js';
import { mountImageControl, type ImageControlProps } from '../../image-control';

export function ImageControl(props: ImageControlProps) {
  let host!: HTMLDivElement;
  let control: ReturnType<typeof mountImageControl> | undefined;
  onMount(() => {
    control = mountImageControl(host, { ...props });
    createEffect(() => control?.update({ label: props.label, value: props.value, options: props.options, onChange: props.onChange }));
  });
  onCleanup(() => control?.destroy());
  return <div ref={host} class="dialkit-image-host" />;
}
