// src/components/DialRoot.tsx
import { useEffect, useState, useRef, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { DialStore, PanelConfig } from '../store/DialStore';
import { TimelineStore } from '../store/TimelineStore';
import { isDevDefault } from '../env';
import { Folder } from './Folder';
import { Panel } from './Panel';
import { ShortcutListener } from './ShortcutListener';
import { TimelineToggleButton } from './Timeline/TimelineToggleButton';
import { blockPanelDragClick, getPanelCorner, getPanelDragHandle, getPanelDragOffset, getPanelDragStart, getPanelOriginX, getPanelOriginY, hasPanelDragMoved } from '../panel-drag';

export type DialPosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
export type DialMode = 'popover' | 'inline';
export type DialTheme = 'light' | 'dark' | 'system';

interface DialRootProps {
  position?: DialPosition;
  defaultOpen?: boolean;
  mode?: DialMode;
  theme?: DialTheme;
  productionEnabled?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function DialRoot({ position = 'top-right', defaultOpen = true, mode = 'popover', theme = 'system', productionEnabled = isDevDefault, onOpenChange }: DialRootProps) {
  if (!productionEnabled) return null;
  const [panels, setPanels] = useState<PanelConfig[]>([]);
  const [timelineCount, setTimelineCount] = useState(0);
  const [mounted, setMounted] = useState(false);
  const inline = mode === 'inline';
  const [shellOpen, setShellOpen] = useState(inline || defaultOpen);

  // Drag state
  const panelRef = useRef<HTMLDivElement>(null);
  const [dragOffset, setDragOffset] = useState<{ x: number; y: number } | null>(null);
  const [activePosition, setActivePosition] = useState(position);
  const lastDragOffset = useRef<{ x: number; y: number } | null>(null);
  const draggingRef = useRef(false);
  const dragStartRef = useRef<{ pointerX: number; pointerY: number; elX: number; elY: number } | null>(null);
  const didDragRef = useRef(false);
  const dragTargetRef = useRef<HTMLElement | null>(null);
  const panelOpenStatesRef = useRef<Map<string, boolean>>(new Map());
  const rootOpenRef = useRef<boolean | null>(null);

  // Subscribe to registered editing surfaces. Timeline-backed panels render
  // in DialTimeline, but their presence adds a visibility toggle here.
  useEffect(() => {
    setMounted(true);
    setPanels(DialStore.getPanels('panel'));
    setTimelineCount(TimelineStore.getTimelines().length);

    const unsubscribePanels = DialStore.subscribeGlobal(() => {
      setPanels(DialStore.getPanels('panel'));
    });
    const unsubscribeTimelines = TimelineStore.subscribeGlobal(() => {
      setTimelineCount(TimelineStore.getTimelines().length);
    });

    return () => {
      unsubscribePanels();
      unsubscribeTimelines();
    };
  }, []);

  useEffect(() => {
    const fallbackOpen = inline || defaultOpen;
    const nextStates = new Map<string, boolean>();
    for (const panel of panels) {
      nextStates.set(panel.id, panelOpenStatesRef.current.get(panel.id) ?? DialStore.getPanelOpen(panel.id) ?? fallbackOpen);
    }
    panelOpenStatesRef.current = nextStates;
    rootOpenRef.current = Array.from(nextStates.values()).some(Boolean);
  }, [defaultOpen, inline, panels]);

  // Watch for panel open/close — snap to corner on open, restore drag position on close
  useEffect(() => {
    if (!panelRef.current || inline) return;
    const observer = new MutationObserver(() => {
      const inners = panelRef.current?.querySelectorAll('.dialkit-panel-inner');
      if (!inners || inners.length === 0) return;
      const collapsed = Array.from(inners).every(
        (el) => el.getAttribute('data-collapsed') === 'true'
      );
      const currentDragOffset = dragOffset;

      if (!collapsed) {
        // Opening — save drag position, determine corner, snap
        if (currentDragOffset) {
          lastDragOffset.current = currentDragOffset;
          setActivePosition(getPanelCorner(position, currentDragOffset));
        } else {
          setActivePosition(position);
        }
        setDragOffset(null);
      } else if (currentDragOffset) {
        lastDragOffset.current = currentDragOffset;
      } else if (lastDragOffset.current) {
        // Closing — restore the dragged position
        setDragOffset(lastDragOffset.current);
      }
    });
    observer.observe(panelRef.current, { subtree: true, attributes: true, attributeFilter: ['data-collapsed'] });
    return () => observer.disconnect();
  }, [inline, dragOffset, position]);

  const handlePointerDown = useCallback((e: React.PointerEvent) => {
    const panel = panelRef.current;
    const handle = getPanelDragHandle(e.target, panel);
    if (!panel || !handle) return;

    dragTargetRef.current = handle;
    dragStartRef.current = getPanelDragStart(e.clientX, e.clientY, panel);
    didDragRef.current = false;
    draggingRef.current = true;
    handle.setPointerCapture(e.pointerId);
  }, []);

  const handlePointerMove = useCallback((e: React.PointerEvent) => {
    if (!draggingRef.current || !dragStartRef.current) return;

    if (!didDragRef.current && !hasPanelDragMoved(dragStartRef.current, e.clientX, e.clientY)) return;
    didDragRef.current = true;

    setDragOffset(getPanelDragOffset(dragStartRef.current, e.clientX, e.clientY));
  }, []);

  const handlePointerUp = useCallback((e: React.PointerEvent) => {
    if (!draggingRef.current) return;
    draggingRef.current = false;
    dragStartRef.current = null;
    const dragTarget = dragTargetRef.current;

    if (dragTarget?.hasPointerCapture(e.pointerId)) {
      dragTarget.releasePointerCapture(e.pointerId);
    }

    // If we actually dragged, prevent the click from opening the panel
    if (didDragRef.current) {
      e.stopPropagation();
      if (dragTarget) {
        blockPanelDragClick(dragTarget);
      }
    }
    dragTargetRef.current = null;
  }, []);

  const handlePanelOpenChange = useCallback((panelId: string, open: boolean) => {
    panelOpenStatesRef.current.set(panelId, open);
    const fallbackOpen = inline || defaultOpen;
    const nextRootOpen = panels.some((panel) => (
      panelOpenStatesRef.current.get(panel.id) ?? fallbackOpen
    ));

    if (rootOpenRef.current === nextRootOpen) return;
    rootOpenRef.current = nextRootOpen;
    onOpenChange?.(nextRootOpen);
  }, [defaultOpen, inline, onOpenChange, panels]);

  const handleRootOpenChange = useCallback((open: boolean) => {
    setShellOpen(open);
    if (rootOpenRef.current === open) return;
    rootOpenRef.current = open;
    onOpenChange?.(open);
  }, [onOpenChange]);

  useEffect(() => DialStore.subscribePanelOpen((id, open) => {
    if (!panels.some(panel => panel.id === id)) return;
    if (panels.length > 1 && open) handleRootOpenChange(true);
    else if (panels.length === 1) handlePanelOpenChange(id, open);
  }), [panels, handleRootOpenChange, handlePanelOpenChange]);

  // Don't render on server
  if (!mounted || typeof window === 'undefined') {
    return null;
  }

  // Don't render if no editing surfaces are registered.
  if (panels.length === 0 && timelineCount === 0) {
    return null;
  }

  const dragStyle = dragOffset ? {
    top: dragOffset.y,
    left: dragOffset.x,
    right: 'auto' as const,
    bottom: 'auto' as const,
  } : undefined;
  const originX = getPanelOriginX(activePosition, dragOffset);
  const originY = getPanelOriginY(activePosition, dragOffset);
  const hasMultiplePanels = panels.length > 1;
  const timelineToggle = timelineCount > 0 ? <TimelineToggleButton /> : null;

  const content = (
  <ShortcutListener>
    <div className="dialkit-root" data-mode={mode} data-theme={theme}>
      <div
        ref={panelRef}
        className="dialkit-panel"
        data-position={inline ? undefined : (dragOffset ? undefined : activePosition)}
        data-origin-x={inline ? undefined : originX}
        data-origin-y={inline ? undefined : originY}
        data-mode={mode}
        data-multiple={hasMultiplePanels ? 'true' : undefined}
        style={dragStyle}
        onPointerDown={!inline ? handlePointerDown : undefined}
        onPointerMove={!inline ? handlePointerMove : undefined}
        onPointerUp={!inline ? handlePointerUp : undefined}
        onPointerCancel={!inline ? handlePointerUp : undefined}
      >
        {panels.length === 0 ? (
          <div className="dialkit-panel-wrapper">
            <Folder
              title="DialKit"
              open={shellOpen}
              defaultOpen={inline || defaultOpen}
              isRoot={true}
              inline={inline}
              onOpenChange={handleRootOpenChange}
              toolbar={timelineToggle}
            >
              <div className="dialkit-timeline-toolkit-only">Timeline</div>
            </Folder>
          </div>
        ) : hasMultiplePanels ? (
          <div className="dialkit-panel-wrapper">
            <Folder
              title="DialKit"
              open={shellOpen}
              defaultOpen={inline || defaultOpen}
              isRoot={true}
              inline={inline}
              onOpenChange={handleRootOpenChange}
              toolbar={timelineToggle}
            >
              {panels.map((panel) => (
                <Panel
                  key={panel.id}
                  panel={panel}
                  defaultOpen={true}
                  variant="section"
                />
              ))}
            </Folder>
          </div>
        ) : (
          panels.map((panel) => (
            <Panel
              key={panel.id}
              panel={panel}
              defaultOpen={inline || defaultOpen}
              inline={inline}
              toolbarExtra={timelineToggle}
              onOpenChange={(open) => handlePanelOpenChange(panel.id, open)}
            />
          ))
        )}
      </div>
    </div>
  </ShortcutListener>
  );

  if (inline) {
    return content;
  }

  return createPortal(content, document.body);
}

// src/svelte/components/DialRoot.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { DialStore } from 'dialkit/store';
  import type { PanelConfig } from 'dialkit/store';
  import { TimelineStore } from 'dialkit/timeline';
  import type { TimelineMeta } from 'dialkit/timeline';
  import { themeCSS } from '../theme-css';
  import Portal from '../Portal.svelte';
  import Folder from './Folder.svelte';
  import Panel from './Panel.svelte';
  import TimelineToggleButton from './Timeline/TimelineToggleButton.svelte';
  import ShortcutListener from './ShortcutListener.svelte';
  import {
    blockPanelDragClick,
    getPanelCorner,
    getPanelDragHandle,
    getPanelDragOffset,
    getPanelDragStart,
    getPanelOriginX,
    getPanelOriginY,
    hasPanelDragMoved,
    type PanelDragOffset,
    type PanelDragStart,
  } from '../../panel-drag';

  export type DialPosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
  export type DialMode = 'popover' | 'inline';
  export type DialTheme = 'light' | 'dark' | 'system';

  const nodeEnv = (globalThis as typeof globalThis & { process?: { env?: { NODE_ENV?: string } } }).process?.env?.NODE_ENV;
  const viteMode = (import.meta as { env?: { MODE?: string } }).env?.MODE;
  const isDevDefault = nodeEnv
    ? nodeEnv !== 'production'
    : viteMode
      ? viteMode !== 'production'
      : true;

  let { position = 'top-right', defaultOpen = true, mode = 'popover', theme = 'system' as DialTheme, productionEnabled = isDevDefault, onOpenChange } = $props<{
    position?: DialPosition;
    defaultOpen?: boolean;
    mode?: DialMode;
    theme?: DialTheme;
    productionEnabled?: boolean;
    onOpenChange?: (open: boolean) => void;
  }>();

  const inline = $derived(mode === 'inline');
  let shellOpen = $state(untrack(() => mode === 'inline' || defaultOpen));

  let panels = $state<PanelConfig[]>([]);
  let timelines = $state<TimelineMeta[]>([]);
  let mounted = $state(false);
  let panelRef = $state<HTMLDivElement>();
  let dragOffset = $state<PanelDragOffset | null>(null);
  let activePosition = $state<DialPosition>(position);
  let lastDragOffset: PanelDragOffset | null = null;
  let dragging = false;
  let dragStart: PanelDragStart | null = null;
  let didDrag = false;
  let dragTarget: HTMLElement | null = null;
  let panelOpenStates = new Map<string, boolean>();
  let rootOpen: boolean | undefined;

  const dragStyle = $derived(
    dragOffset
      ? `top:${dragOffset.y}px;left:${dragOffset.x}px;right:auto;bottom:auto;`
      : undefined
  );
  const originX = $derived(inline ? undefined : getPanelOriginX(activePosition, dragOffset));
  const originY = $derived(inline ? undefined : getPanelOriginY(activePosition, dragOffset));

  $effect(() => {
    if (typeof document === 'undefined') return;
    const id = 'dialkit-theme';
    if (!document.getElementById(id)) {
      const style = document.createElement('style');
      style.id = id;
      style.textContent = themeCSS;
      document.head.appendChild(style);
    }
  });

  $effect(() => {
    if (typeof window === 'undefined') return;

    mounted = true;
    panels = DialStore.getPanels('panel');
    timelines = TimelineStore.getTimelines();

    const unsubscribePanels = DialStore.subscribeGlobal(() => {
      panels = DialStore.getPanels('panel');
    });
    const unsubscribeOpen = DialStore.subscribePanelOpen((id, open) => {
      if (!panels.some(panel => panel.id === id)) return;
      if (panels.length > 1 && open) handleRootOpenChange(true);
      else if (panels.length === 1) handlePanelOpenChange(id, open);
    });
    const unsubscribeTimelines = TimelineStore.subscribeGlobal(() => {
      timelines = TimelineStore.getTimelines();
    });

    return () => {
      unsubscribePanels();
      unsubscribeTimelines();
      unsubscribeOpen();
    };
  });

  $effect(() => {
    const fallbackOpen = inline || defaultOpen;
    const nextStates = new Map<string, boolean>();
    for (const panel of panels) {
      nextStates.set(panel.id, panelOpenStates.get(panel.id) ?? DialStore.getPanelOpen(panel.id) ?? fallbackOpen);
    }
    panelOpenStates = nextStates;
    rootOpen = Array.from(nextStates.values()).some(Boolean);
  });

  $effect(() => {
    if (inline || !panelRef) return;

    const observer = new MutationObserver(() => {
      const inners = panelRef?.querySelectorAll('.dialkit-panel-inner');
      if (!inners || inners.length === 0) return;
      const collapsed = Array.from(inners).every((el) => el.getAttribute('data-collapsed') === 'true');

      if (!collapsed) {
        if (dragOffset) {
          lastDragOffset = dragOffset;
          activePosition = getPanelCorner(position, dragOffset);
        } else {
          activePosition = position;
        }
        dragOffset = null;
      } else if (dragOffset) {
        lastDragOffset = dragOffset;
      } else if (lastDragOffset) {
        dragOffset = lastDragOffset;
      }
    });

    observer.observe(panelRef, { subtree: true, attributes: true, attributeFilter: ['data-collapsed'] });
    return () => observer.disconnect();
  });

  function handlePointerDown(event: PointerEvent) {
    const panel = panelRef ?? null;
    const handle = getPanelDragHandle(event.target, panel);
    if (!panel || !handle) return;

    dragTarget = handle;
    dragStart = getPanelDragStart(event.clientX, event.clientY, panel);
    didDrag = false;
    dragging = true;
    handle.setPointerCapture(event.pointerId);
  }

  function handlePointerMove(event: PointerEvent) {
    if (!dragging || !dragStart) return;

    if (!didDrag && !hasPanelDragMoved(dragStart, event.clientX, event.clientY)) return;
    didDrag = true;

    dragOffset = getPanelDragOffset(dragStart, event.clientX, event.clientY);
  }

  function handlePointerUp(event: PointerEvent) {
    if (!dragging) return;
    dragging = false;
    dragStart = null;
    const handle = dragTarget;

    if (handle?.hasPointerCapture(event.pointerId)) {
      handle.releasePointerCapture(event.pointerId);
    }

    if (didDrag) {
      event.stopPropagation();
      if (handle) {
        blockPanelDragClick(handle);
      }
    }

    dragTarget = null;
  }

  function handlePanelOpenChange(panelId: string, open: boolean) {
    panelOpenStates.set(panelId, open);
    const fallbackOpen = inline || defaultOpen;
    const nextRootOpen = panels.some((panel) => (
      panelOpenStates.get(panel.id) ?? fallbackOpen
    ));

    if (rootOpen === nextRootOpen) return;
    rootOpen = nextRootOpen;
    onOpenChange?.(nextRootOpen);
  }

  function handleRootOpenChange(open: boolean) {
    shellOpen = open;
    if (rootOpen === open) return;
    rootOpen = open;
    onOpenChange?.(open);
  }

</script>

{#snippet timelineToolbar()}
  {#if timelines.length > 0}
    <TimelineToggleButton />
  {/if}
{/snippet}

{#if productionEnabled && mounted && (panels.length > 0 || timelines.length > 0)}
  {#snippet content()}
    <ShortcutListener>
      <div class="dialkit-root" data-mode={mode} data-theme={theme}>
        <div
          bind:this={panelRef}
          class="dialkit-panel"
          data-mode={mode}
          data-position={inline ? undefined : (dragOffset ? undefined : activePosition)}
          data-origin-x={originX}
          data-origin-y={originY}
          data-multiple={panels.length > 1 ? 'true' : undefined}
          style={dragStyle}
          onpointerdown={!inline ? handlePointerDown : undefined}
          onpointermove={!inline ? handlePointerMove : undefined}
          onpointerup={!inline ? handlePointerUp : undefined}
          onpointercancel={!inline ? handlePointerUp : undefined}
        >
          {#if panels.length === 0}
            <div class="dialkit-panel-wrapper">
              <Folder
                title="DialKit"
                open={shellOpen}
                defaultOpen={inline || defaultOpen}
                isRoot={true}
                {inline}
                onOpenChange={handleRootOpenChange}
              >
                {#snippet toolbar()}
                  {@render timelineToolbar()}
                {/snippet}
                <div class="dialkit-timeline-toolkit-only">Timeline</div>
              </Folder>
            </div>
          {:else if panels.length > 1}
            <div class="dialkit-panel-wrapper">
              <Folder
                title="DialKit"
                open={shellOpen}
                defaultOpen={inline || defaultOpen}
                isRoot={true}
                {inline}
                onOpenChange={handleRootOpenChange}
              >
                {#snippet toolbar()}
                  {@render timelineToolbar()}
                {/snippet}
                {#each panels as panel (panel.id)}
                  <Panel
                    {panel}
                    defaultOpen={true}
                    variant="section"
                  />
                {/each}
              </Folder>
            </div>
          {:else}
            {#each panels as panel (panel.id)}
              <Panel
                {panel}
                defaultOpen={inline || defaultOpen}
                {inline}
                toolbarExtra={timelineToolbar}
                onOpenChange={(open) => handlePanelOpenChange(panel.id, open)}
              />
            {/each}
          {/if}
        </div>
      </div>
    </ShortcutListener>
  {/snippet}

  {#if inline}
    {@render content()}
  {:else}
    <Portal target="body">
      {@render content()}
    </Portal>
  {/if}
{/if}
