// src/solid/components/ControlRenderer.tsx
import { For } from 'solid-js';
import { DialStore } from '../../store/DialStore';
import type {
  ControlMeta,
  DialValue,
  SpringConfig,
  TransitionConfig,
} from '../../store/DialStore';
import { useShortcutContext } from './ShortcutListener';
import { ColorControl } from './ColorControl';
import { ImageControl } from './ImageControl';
import { DialPad } from './DialPad';
import type { DialPadValue } from '../../dial-pad';
import { Folder } from './Folder';
import { SelectControl } from './SelectControl';
import { Slider } from './Slider';
import { SpringControl } from './SpringControl';
import { TextControl } from './TextControl';
import { Toggle } from './Toggle';
import { TransitionControl, type TransitionDurationControl } from './TransitionControl';

interface ControlRendererProps {
  panelId: string;
  controls: ControlMeta[];
  values: Record<string, DialValue>;
  transitionDuration?: TransitionDurationControl;
}

export function ControlRenderer(props: ControlRendererProps) {
  const shortcut = useShortcutContext();

  const renderControl = (control: ControlMeta) => {
    const value = () => props.values[control.path];
    switch (control.type) {
      case 'slider':
        return (
          <Slider
            label={control.label}
            value={value() as number}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
            min={control.min}
            max={control.max}
            step={control.step}
            shortcut={control.shortcut}
            shortcutActive={shortcut().activePanelId === props.panelId && shortcut().activePath === control.path}
          />
        );
      case 'toggle':
        return (
          <Toggle
            label={control.label}
            checked={value() as boolean}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
            shortcut={control.shortcut}
            shortcutActive={shortcut().activePanelId === props.panelId && shortcut().activePath === control.path}
          />
        );
      case 'spring':
        return (
          <SpringControl
            panelId={props.panelId}
            path={control.path}
            label={control.label}
            spring={value() as SpringConfig}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
          />
        );
      case 'transition':
        return (
          <TransitionControl
            panelId={props.panelId}
            path={control.path}
            label={control.label}
            value={value() as TransitionConfig}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
            durationControl={props.transitionDuration}
          />
        );
      case 'folder':
        return (
          <Folder title={control.label} defaultOpen={control.defaultOpen ?? true}>
            <For each={control.children ?? []}>{renderControl}</For>
          </Folder>
        );
      case 'text':
        return (
          <TextControl
            label={control.label}
            value={value() as string}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
            placeholder={control.placeholder}
          />
        );
      case 'select':
        return (
          <SelectControl
            label={control.label}
            value={value() as string}
            options={control.options ?? []}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
          />
        );
      case 'color':
        return (
          <ColorControl
            label={control.label}
            value={value() as string}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
          />
        );
      case 'image':
        return (
          <ImageControl
            options={control.options}
            label={control.label}
            value={value() as string}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
          />
        );
      case 'pad':
        return (
          <DialPad
            label={control.label}
            value={value() as DialPadValue}
            x={control.pad?.x}
            y={control.pad?.y}
            labels={control.pad?.labels}
            onChange={(next) => DialStore.updateValue(props.panelId, control.path, next)}
          />
        );
      case 'action':
        return (
          <button class="dialkit-button" onClick={() => DialStore.triggerAction(props.panelId, control.path)}>
            {control.label}
          </button>
        );
      default:
        return null;
    }
  };

  return <For each={props.controls}>{renderControl}</For>;
}

// src/components/ControlRenderer.tsx
import { useContext } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { DialStore, ControlMeta, DialValue, SpringConfig, TransitionConfig } from '../store/DialStore';
import { CONTROL_ANIM } from './control-motion';
import { ShortcutContext } from './ShortcutListener';
import { Folder } from './Folder';
import { Slider } from './Slider';
import { Toggle } from './Toggle';
import { SpringControl } from './SpringControl';
import { TransitionControl } from './TransitionControl';
import { TextControl } from './TextControl';
import { SelectControl, SelectPills } from './SelectControl';
import { ColorControl } from './ColorControl';
import { ImageControl } from './ImageControl';
import { DialPad } from './DialPad';
import type { DialPadValue } from '../dial-pad';

interface ControlRendererProps {
  panelId: string;
  controls: ControlMeta[];
  values: Record<string, DialValue>;
  /** Optional timeline-owned duration rendered inside the transition editor. */
  transitionDuration?: {
    value: number;
    onChange: (value: number) => void;
    min?: number;
    max?: number;
    step?: number;
  };
  /** Cap (seconds) on the settle a physics spring's params may produce —
   *  threaded into TransitionControl's physics sliders (see its
   *  physicsSettleCap doc). */
  physicsSettleCap?: number;
  /**
   * Opt-in enter/exit animation for each rendered control (used so
   * conditionally-visible controls animate in/out when their `visibleWhen`
   * rule flips). Defaults to false so callers like the Timeline clip
   * popover stay vanilla — no motion wrapper, no AnimatePresence.
   */
  animateControls?: boolean;
  /**
   * Path of the currently-open top-level (depth 0) folder when the caller is
   * running accordion mode. Only consulted when `onAccordionToggle` is also
   * provided; nested folders (depth > 0) always stay independent.
   */
  accordionOpenPath?: string | null;
  /** Fired when a depth-0 folder is toggled in accordion mode. Receives the folder's path and its requested next open state. */
  onAccordionToggle?: (path: string, next: boolean) => void;
}

// Renders a ControlMeta tree with the standard DialKit controls.
// Shared by the panel and the timeline clip popover.
export function ControlRenderer({
  panelId,
  controls,
  values,
  transitionDuration,
  physicsSettleCap,
  animateControls = false,
  accordionOpenPath,
  onAccordionToggle,
}: ControlRendererProps) {
  const shortcutCtx = useContext(ShortcutContext);

  const renderControlInner = (control: ControlMeta, depth: number) => {
    const value = values[control.path];

    switch (control.type) {
      case 'slider':
        return (
          <Slider
            key={control.path}
            label={control.label}
            value={value as number}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
            min={control.min}
            max={control.max}
            step={control.step}
            shortcut={control.shortcut}
            shortcutActive={shortcutCtx.activePanelId === panelId && shortcutCtx.activePath === control.path}
          />
        );

      case 'toggle':
        return (
          <Toggle
            key={control.path}
            label={control.label}
            checked={value as boolean}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
            shortcut={control.shortcut}
            shortcutActive={shortcutCtx.activePanelId === panelId && shortcutCtx.activePath === control.path}
          />
        );

      case 'spring':
        return (
          <SpringControl
            key={control.path}
            panelId={panelId}
            path={control.path}
            label={control.label}
            spring={value as SpringConfig}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
          />
        );

      case 'transition':
        return (
          <TransitionControl
            key={control.path}
            panelId={panelId}
            path={control.path}
            label={control.label}
            value={value as TransitionConfig}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
            durationControl={transitionDuration}
            physicsSettleCap={physicsSettleCap}
          />
        );

      case 'folder': {
        // Controlled accordion open state only applies to depth-0 folders
        // when the caller opted into accordion mode by passing
        // onAccordionToggle. Nested folders always stay independent
        // (uncontrolled) regardless of mode.
        const controlledProps =
          depth === 0 && onAccordionToggle
            ? {
                open: accordionOpenPath === control.path,
                onOpenChange: (next: boolean) => onAccordionToggle(control.path, next),
              }
            : {};
        const children = control.children?.map((child) => renderControl(child, depth + 1));
        return (
          <Folder key={control.path} title={control.label} defaultOpen={control.defaultOpen ?? true} {...controlledProps}>
            {animateControls ? <AnimatePresence initial={false}>{children}</AnimatePresence> : children}
          </Folder>
        );
      }

      case 'text':
        return (
          <TextControl
            key={control.path}
            label={control.label}
            value={value as string}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
            placeholder={control.placeholder}
          />
        );

      case 'select':
        if (control.display === 'pills') {
          return (
            <SelectPills
              key={control.path}
              label={control.label}
              value={value as string}
              options={control.options ?? []}
              onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
              hideLabel={control.hideLabel}
            />
          );
        }
        return (
          <SelectControl
            key={control.path}
            label={control.label}
            value={value as string}
            options={control.options ?? []}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
          />
        );

      case 'color':
        return (
          <ColorControl
            key={control.path}
            label={control.label}
            value={value as string}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
          />
        );

      case 'image':
        return (
          <ImageControl
            key={control.path}
            options={control.options}
            label={control.label}
            value={value as string}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
          />
        );

      case 'pad':
        return (
          <DialPad
            key={control.path}
            label={control.label}
            value={value as DialPadValue}
            x={control.pad?.x}
            y={control.pad?.y}
            labels={control.pad?.labels}
            onChange={(v) => DialStore.updateValue(panelId, control.path, v)}
          />
        );

      case 'action':
        return (
          <button
            key={control.path}
            className="dialkit-button"
            onClick={() => DialStore.triggerAction(panelId, control.path)}
          >
            {control.label}
          </button>
        );

      default:
        return null;
    }
  };

  const renderControl = (control: ControlMeta, depth = 0) => {
    const inner = renderControlInner(control, depth);
    if (inner === null || !animateControls) return inner;

    // Every control is wrapped in a motion.div so it can animate its
    // enter/exit when conditional visibility hides/shows it. The marker
    // classes let theme.css target folder wrappers specifically (for the
    // adjacent-divider collapse rule) without needing :has(). Spring and
    // transition controls render as Folder internally.
    const isFolder = control.type === 'folder' || control.type === 'spring' || control.type === 'transition';
    const wrapClassName = isFolder
      ? 'dialkit-control-wrap dialkit-control-wrap-folder'
      : 'dialkit-control-wrap';

    return (
      <motion.div key={control.path} className={wrapClassName} {...CONTROL_ANIM}>
        {inner}
      </motion.div>
    );
  };

  if (!animateControls) {
    return <>{controls.map((control) => renderControl(control, 0))}</>;
  }

  return (
    <AnimatePresence initial={false}>
      {controls.map((control) => renderControl(control, 0))}
    </AnimatePresence>
  );
}
