// src/solid/components/DialPad.tsx
import { createEffect, onCleanup, onMount } from 'solid-js';
import { mountDialPad, type DialPadProps } from '../../dial-pad-control';

export function DialPad(props: DialPadProps) {
  let host!: HTMLDivElement;
  let control: ReturnType<typeof mountDialPad> | undefined;
  onMount(() => {
    control = mountDialPad(host, { ...props });
    createEffect(() => control?.update({ label: props.label, value: props.value, x: props.x, y: props.y, labels: props.labels, onChange: props.onChange }));
  });
  onCleanup(() => control?.destroy());
  return <div ref={host} class="dialkit-pad-host" />;
}

// src/components/DialPad.tsx
import { useEffect, useRef } from 'react';
import { mountDialPad, type DialPadProps } from '../dial-pad-control';

export function DialPad(props: DialPadProps) {
  const host = useRef<HTMLDivElement>(null);
  const control = useRef<ReturnType<typeof mountDialPad>>();
  const latest = useRef(props);
  latest.current = props;
  useEffect(() => {
    control.current = mountDialPad(host.current!, latest.current);
    return () => control.current?.destroy();
  }, []);
  useEffect(() => { control.current?.update(props); });
  return <div ref={host} className="dialkit-pad-host" />;
}
