// src/svelte/components/SelectControl.svelte
<script lang="ts">
  import { Spring } from 'svelte/motion';
  import Portal from '../Portal.svelte';
  import { dropdownTransition } from './transitions';
  import { getDialKitPortalRoot, getDropdownPosition, observeDropdownPosition, type DropdownPosition } from '../../dropdown-position';
  import { ICON_CHEVRON } from '../../icons';

  type SelectOption = string | { value: string; label: string };

  let { label, value, options, onChange } = $props<{
    label: string;
    value: string;
    options: SelectOption[];
    onChange: (value: string) => void;
  }>();

  let isOpen = $state(false);
  let pos = $state<DropdownPosition | null>(null);
  let portalTarget = $state<HTMLElement | null>(null);
  let triggerRef: HTMLButtonElement | undefined;
  let dropdownRef: HTMLDivElement | undefined;

  const chevronRotation = new Spring(0, { stiffness: 0.2, damping: 0.6 });

  const toTitleCase = (s: string) => s.replace(/\b\w/g, (c) => c.toUpperCase());

  const normalized = $derived(
    options.map((opt: SelectOption) =>
      typeof opt === 'string' ? { value: opt, label: toTitleCase(opt) } : opt
    )
  );

  const selectedOption = $derived(normalized.find((o: { value: string; label: string }) => o.value === value));

  const updatePos = () => {
    if (!triggerRef || !portalTarget || typeof window === 'undefined') return;
    const dropdownHeight = dropdownRef ? dropdownRef.scrollHeight + 2 : 10 + normalized.length * 36;
    pos = getDropdownPosition(triggerRef, portalTarget, { dropdownHeight, fixed: true });
  };

  const openDropdown = () => {
    updatePos();
    isOpen = true;
  };

  const closeDropdown = () => {
    isOpen = false;
  };

  const dropdownStyle = $derived.by(() => {
    if (!pos || typeof window === 'undefined') return '';

    if (pos.above) {
      return `position:fixed;left:${pos.left}px;top:${pos.top}px;width:${pos.width}px;max-height:${pos.maxHeight}px;transform-origin:bottom;`;
    }

    return `position:fixed;left:${pos.left}px;top:${pos.top}px;width:${pos.width}px;max-height:${pos.maxHeight}px;transform-origin:top;`;
  });

  $effect(() => {
    if (typeof document === 'undefined' || !triggerRef) return;

    portalTarget = getDialKitPortalRoot(triggerRef) ?? document.body;
  });

  $effect(() => {
    chevronRotation.set(isOpen ? 180 : 0);
  });

  $effect(() => {
    if (!isOpen || typeof window === 'undefined') return;

    const handleViewportChange = () => updatePos();

    const handleClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (triggerRef?.contains(target) || dropdownRef?.contains(target)) return;
      closeDropdown();
    };

    const stopPosition = observeDropdownPosition(triggerRef!, updatePos, () => dropdownRef);
    document.addEventListener('mousedown', handleClick);
    window.addEventListener('resize', handleViewportChange);
    window.addEventListener('scroll', handleViewportChange, true);

    return () => {
      stopPosition();
      document.removeEventListener('mousedown', handleClick);
      window.removeEventListener('resize', handleViewportChange);
      window.removeEventListener('scroll', handleViewportChange, true);
    };
  });
</script>

<div class="dialkit-select-row">
  <button
    bind:this={triggerRef}
    class="dialkit-select-trigger"
    onclick={() => (isOpen ? closeDropdown() : openDropdown())}
    data-open={String(isOpen)}
  >
    <span class="dialkit-select-label">{label}</span>
    <div class="dialkit-select-right">
      <span class="dialkit-select-value">{selectedOption?.label ?? value}</span>
      <svg
        class="dialkit-select-chevron"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2.5"
        stroke-linecap="round"
        stroke-linejoin="round"
        style:transform={`rotate(${chevronRotation.current}deg)`}
      >
        <path d={ICON_CHEVRON} />
      </svg>
    </div>
  </button>

  {#if portalTarget}
    <Portal target={portalTarget}>
      {#if isOpen && pos}
        <div
          bind:this={dropdownRef}
          class="dialkit-select-dropdown"
          style={dropdownStyle}
          transition:dropdownTransition={{ above: pos.above }}
        >
          {#each normalized as option (option.value)}
            <button
              class="dialkit-select-option"
              data-selected={String(option.value === value)}
              onclick={() => {
                onChange(option.value);
                closeDropdown();
              }}
            >
              {option.label}
            </button>
          {/each}
        </div>
      {/if}
    </Portal>
  {/if}
</div>

// src/components/SelectControl.tsx
import { useState, useRef, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'motion/react';
import { getDialKitPortalRoot, getDropdownPosition, observeDropdownPosition, type DropdownPosition } from '../dropdown-position';
import { ICON_CHEVRON } from '../icons';

type SelectOption = string | { value: string; label: string };

interface SelectControlProps {
  label: string;
  value: string;
  options: SelectOption[];
  onChange: (value: string) => void;
}

function toTitleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

function normalizeOptions(options: SelectOption[]): { value: string; label: string }[] {
  return options.map((opt) =>
    typeof opt === 'string' ? { value: opt, label: toTitleCase(opt) } : opt
  );
}

export function SelectControl({ label, value, options, onChange }: SelectControlProps) {
  const [isOpen, setIsOpen] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const [portalTarget, setPortalTarget] = useState<HTMLElement | null>(null);
  const [pos, setPos] = useState<DropdownPosition | null>(null);
  const normalized = normalizeOptions(options);
  const selectedOption = normalized.find((o) => o.value === value);

  const updatePos = useCallback(() => {
    const el = triggerRef.current;
    if (!el || !portalTarget) return;
    // Estimate dropdown height: 8px padding + 36px per option
    const dropdownHeight = dropdownRef.current ? dropdownRef.current.scrollHeight + 2 : 10 + normalized.length * 36;
    setPos(getDropdownPosition(el, portalTarget, { dropdownHeight, fixed: true }));
  }, [normalized.length, portalTarget]);

  // Resolve portal target (closest .dialkit-root)
  useEffect(() => {
    setPortalTarget(getDialKitPortalRoot(triggerRef.current) ?? document.body);
  }, []);

  // Position dropdown when opening
  useEffect(() => {
    if (!isOpen) return;
    if (!triggerRef.current) return;
    return observeDropdownPosition(triggerRef.current, updatePos, () => dropdownRef.current);
  }, [isOpen, updatePos]);

  // Close on click outside
  useEffect(() => {
    if (!isOpen) return;

    const handleClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        triggerRef.current && !triggerRef.current.contains(target) &&
        dropdownRef.current && !dropdownRef.current.contains(target)
      ) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [isOpen]);

  return (
    <div className="dialkit-select-row">
      <button
        ref={triggerRef}
        className="dialkit-select-trigger"
        onClick={() => setIsOpen(!isOpen)}
        data-open={String(isOpen)}
      >
        <span className="dialkit-select-label">{label}</span>
        <div className="dialkit-select-right">
          <span className="dialkit-select-value">{selectedOption?.label ?? value}</span>
          <motion.svg
            className="dialkit-select-chevron"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
            animate={{ rotate: isOpen ? 180 : 0 }}
            transition={{ type: 'spring', visualDuration: 0.2, bounce: 0.15 }}
          >
            <path d={ICON_CHEVRON} />
          </motion.svg>
        </div>
      </button>

      {portalTarget && createPortal(
        <AnimatePresence>
          {isOpen && pos && (
            <motion.div
              ref={dropdownRef}
              className="dialkit-select-dropdown"
              initial={{ opacity: 0, y: pos.above ? 8 : -8, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: pos.above ? 8 : -8, scale: 0.95 }}
              transition={{ type: 'spring', visualDuration: 0.15, bounce: 0 }}
              style={{
                position: 'fixed',
                left: pos.left,
                top: pos.top,
                width: pos.width,
                maxHeight: pos.maxHeight,
                transformOrigin: pos.above ? 'bottom' : 'top',
              }}
            >
              {normalized.map((option) => (
                <button
                  key={option.value}
                  className="dialkit-select-option"
                  data-selected={String(option.value === value)}
                  onClick={() => {
                    onChange(option.value);
                    setIsOpen(false);
                  }}
                >
                  {option.label}
                </button>
              ))}
            </motion.div>
          )}
        </AnimatePresence>,
        portalTarget
      )}
    </div>
  );
}
