// src/solid/components/SelectControl.tsx
import { observeDropdownKeyboard } from '../../dropdown-keyboard';
import { openDropdownOnKey } from '../../control-keyboard';
import { createSignal, createEffect, on, onMount, onCleanup, Show, For } from 'solid-js';
import { Portal } from 'solid-js/web';
import { animate } from 'motion';
import { getDialKitPortalRoot, getDropdownPosition, observeDropdownPosition, type DropdownPosition } from '../../dropdown-position';
import { ICON_CHEVRON } from '../../icons';
import { createDropdownDismiss, createDropdownPresence, type AnimationHandle } from '../primitives';

type SelectOption = string | { value: string; label: string };

interface SelectControlProps {
  label: string;
  value: string;
  options: SelectOption[];
  onChange: (value: string) => void;
}

function toTitleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

function normalizeOptions(options: SelectOption[]): { value: string; label: string }[] {
  return options.map((opt) =>
    typeof opt === 'string' ? { value: opt, label: toTitleCase(opt) } : opt
  );
}

export function SelectControl(props: SelectControlProps) {
  const [pos, setPos] = createSignal<DropdownPosition | null>(null);
  const [portalTarget, setPortalTarget] = createSignal<HTMLElement | null>(null);
  let triggerRef!: HTMLButtonElement;
  let dropdownRef: HTMLDivElement | undefined;
  let chevronRef!: SVGSVGElement;
  let chevronAnim: AnimationHandle | null = null;

  const normalized = () => normalizeOptions(props.options);
  const selectedOption = () => normalized().find((o) => o.value === props.value);

  const dropdown = createDropdownPresence((el, done) =>
    animate(
      el,
      { opacity: 0, y: (pos()?.above ?? false) ? 8 : -8, scale: 0.95 },
      { type: 'spring', visualDuration: 0.15, bounce: 0, onComplete: done }
    )
  );

  onMount(() => {
    setPortalTarget(getDialKitPortalRoot(triggerRef) ?? document.body);
    onCleanup(() => chevronAnim?.stop());
  });

  // Chevron renders at its resting angle; only animate on changes.
  createEffect(on(dropdown.isOpen, (open) => {
    if (!chevronRef) return;
    chevronAnim?.stop();
    chevronAnim = animate(
      chevronRef,
      { rotate: open ? 180 : 0 },
      { type: 'spring', visualDuration: 0.2, bounce: 0.15 }
    );
  }, { defer: true }));

  const updatePos = () => {
    const root = portalTarget();
    if (!triggerRef || !root) return;
    const dropdownHeight = dropdownRef?.isConnected ? dropdownRef.scrollHeight + 2 : 10 + normalized().length * 36;
    setPos(getDropdownPosition(triggerRef, root, { dropdownHeight, fixed: true }));
  };

  createEffect(() => {
    if (!dropdown.isOpen() || !triggerRef) return;
    onCleanup(observeDropdownPosition(triggerRef, updatePos, () => dropdownRef));
    onCleanup(observeDropdownKeyboard(triggerRef, () => dropdownRef, dropdown.close));
  });

  const openDropdown = () => {
    updatePos();
    dropdown.open();
  };

  createDropdownDismiss({
    isOpen: dropdown.isOpen,
    contains: (target) => triggerRef?.contains(target) || dropdown.contains(target),
    onDismiss: dropdown.close,
    onViewportChange: updatePos,
  });

  const dropdownStyle = () => {
    const p = pos();
    if (!p) return {};
    return {
      position: 'fixed' as const,
      left: `${p.left}px`,
      top: `${p.top}px`,
      width: `${p.width}px`,
      'max-height': `${p.maxHeight}px`,
      'transform-origin': p.above ? 'bottom' : 'top',
    };
  };

  return (
    <div class="dialkit-select-row">
      <button
        ref={triggerRef}
        class="dialkit-select-trigger"
        onClick={() => dropdown.isOpen() ? dropdown.close() : openDropdown()}
        data-open={String(dropdown.isOpen())}
        type="button" aria-haspopup="listbox" aria-expanded={dropdown.isOpen()} disabled={!props.options.length}
        onKeyDown={(e) => openDropdownOnKey(e, openDropdown)}
      >
        <span class="dialkit-select-label">{props.label}</span>
        <div class="dialkit-select-right">
          <span class="dialkit-select-value">{selectedOption()?.label ?? props.value}</span>
          <svg
            ref={chevronRef}
            class="dialkit-select-chevron"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d={ICON_CHEVRON} />
          </svg>
        </div>
      </button>

      <Show when={!!portalTarget()}>
        <Portal mount={portalTarget()!}>
          <Show when={dropdown.mounted() && pos()}>
            <div
              ref={(el) => {
                dropdownRef = el;
                dropdown.setRef(el);
                const above = pos()?.above ?? false;
                animate(
                  el,
                  { opacity: [0, 1], y: [above ? 8 : -8, 0], scale: [0.95, 1] },
                  { type: 'spring', visualDuration: 0.15, bounce: 0 }
                );
              }}
              class="dialkit-select-dropdown"
              style={dropdownStyle()}
            >
              <For each={normalized()}>
                {(option) => (
                  <button
                    class="dialkit-select-option"
                    data-selected={String(option.value === props.value)}
                    onClick={() => {
                      props.onChange(option.value);
                      dropdown.close();
                    }}
                  >
                    {option.label}
                  </button>
                )}
              </For>
            </div>
          </Show>
        </Portal>
      </Show>
    </div>
  );
}

// src/components/SelectControl.tsx
import { observeDropdownKeyboard } from '../dropdown-keyboard';
import { openDropdownOnKey } from '../control-keyboard';
import { useState, useRef, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'motion/react';
import { getDialKitPortalRoot, getDropdownPosition, observeDropdownPosition, type DropdownPosition } from '../dropdown-position';
import { ICON_CHEVRON } from '../icons';

type SelectOption = string | { value: string; label: string };

interface SelectControlProps {
  label: string;
  value: string;
  options: SelectOption[];
  onChange: (value: string) => void;
}

function toTitleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

function normalizeOptions(options: SelectOption[]): { value: string; label: string }[] {
  return options.map((opt) =>
    typeof opt === 'string' ? { value: opt, label: toTitleCase(opt) } : opt
  );
}

export function SelectControl({ label, value, options, onChange }: SelectControlProps) {
  const [isOpen, setIsOpen] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const [portalTarget, setPortalTarget] = useState<HTMLElement | null>(null);
  const [pos, setPos] = useState<DropdownPosition | null>(null);
  const normalized = normalizeOptions(options);
  const selectedOption = normalized.find((o) => o.value === value);

  const updatePos = useCallback(() => {
    const el = triggerRef.current;
    if (!el || !portalTarget) return;
    // Estimate dropdown height: 8px padding + 36px per option
    const dropdownHeight = dropdownRef.current ? dropdownRef.current.scrollHeight + 2 : 10 + normalized.length * 36;
    setPos(getDropdownPosition(el, portalTarget, { dropdownHeight, fixed: true }));
  }, [normalized.length, portalTarget]);

  // Resolve portal target (closest .dialkit-root)
  useEffect(() => {
    setPortalTarget(getDialKitPortalRoot(triggerRef.current) ?? document.body);
  }, []);

  // Position dropdown when opening
  useEffect(() => {
    if (!isOpen) return;
    if (!triggerRef.current) return;
    const stopPosition = observeDropdownPosition(triggerRef.current, updatePos, () => dropdownRef.current);
    const stopKeyboard = observeDropdownKeyboard(triggerRef.current, () => dropdownRef.current, () => setIsOpen(false));
    return () => { stopKeyboard(); stopPosition(); };
  }, [isOpen, updatePos]);

  // Close on click outside
  useEffect(() => {
    if (!isOpen) return;

    const handleClick = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        triggerRef.current && !triggerRef.current.contains(target) &&
        dropdownRef.current && !dropdownRef.current.contains(target)
      ) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [isOpen]);

  return (
    <div className="dialkit-select-row">
      <button
        ref={triggerRef}
        className="dialkit-select-trigger"
        onClick={() => setIsOpen(!isOpen)}
        data-open={String(isOpen)}
        type="button" aria-haspopup="listbox" aria-expanded={isOpen} disabled={!options.length}
        onKeyDown={(e) => openDropdownOnKey(e, () => setIsOpen(true))}
      >
        <span className="dialkit-select-label">{label}</span>
        <div className="dialkit-select-right">
          <span className="dialkit-select-value">{selectedOption?.label ?? value}</span>
          <motion.svg
            className="dialkit-select-chevron"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
            animate={{ rotate: isOpen ? 180 : 0 }}
            transition={{ type: 'spring', visualDuration: 0.2, bounce: 0.15 }}
          >
            <path d={ICON_CHEVRON} />
          </motion.svg>
        </div>
      </button>

      {portalTarget && createPortal(
        <AnimatePresence>
          {isOpen && pos && (
            <motion.div
              ref={dropdownRef}
              className="dialkit-select-dropdown"
              initial={{ opacity: 0, y: pos.above ? 8 : -8, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: pos.above ? 8 : -8, scale: 0.95 }}
              transition={{ type: 'spring', visualDuration: 0.15, bounce: 0 }}
              style={{
                position: 'fixed',
                left: pos.left,
                top: pos.top,
                width: pos.width,
                maxHeight: pos.maxHeight,
                transformOrigin: pos.above ? 'bottom' : 'top',
              }}
            >
              {normalized.map((option) => (
                <button
                  key={option.value}
                  className="dialkit-select-option"
                  data-selected={String(option.value === value)}
                  onClick={() => {
                    onChange(option.value);
                    setIsOpen(false);
                  }}
                >
                  {option.label}
                </button>
              ))}
            </motion.div>
          )}
        </AnimatePresence>,
        portalTarget
      )}
    </div>
  );
}
