// src/svelte/components/TextControl.svelte
<script lang="ts">
  let { label, value, onChange, placeholder } = $props<{
    label: string;
    value: string;
    onChange: (value: string) => void;
    placeholder?: string;
  }>();
</script>

<label class="dialkit-text-control">
  <span class="dialkit-text-label">{label}</span>
  <input
    type="text"
    class="dialkit-text-input"
    value={value}
    placeholder={placeholder}
    oninput={(e) => onChange((e.currentTarget as HTMLInputElement).value)}
  />
</label>

// src/components/TextControl.tsx
interface TextControlProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
}

export function TextControl({ label, value, onChange, placeholder }: TextControlProps) {
  return (
    <label className="dialkit-text-control">
      <span className="dialkit-text-label">{label}</span>
      <input
        type="text"
        className="dialkit-text-input"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
      />
    </label>
  );
}
